#!/bin/bash -e
export AWS_DEFAULT_REGION=eu-west-1
export AWS_USER_ARN=arn:aws:iam::244050941743:user/adminEC2
export AWS_DEFAULT_OUTPUT=json
export AWS_SECRET_ACCESS_KEY=8h1k6B13QgM0Jo/UmXvO/sY0MN0GkDrl9qThGHVL
export AWS_ACCESS_KEY_ID=AKIATRUUR24XUUHX4T6K
export AWS_USER_NAME=AdminEC2
